layout_spectrum: 0.8404256
name: cysfilm
title: cysfilm
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.4748203316703439
color:
  brandStrength: 0.8170213
  saturation: 0.4497728
  brandColors:
    - '#F2F2F2'
    - '#00EDED'
    - '#E64C4E'
    - '#EEA7A5'
    - '#6D6D6D'
  lightness: 0.7957447
  rhythmicContrast: 0.3318997
