name: cysfilm
favicon: null
layout_spectrum: 0.67138
typography_spectrum: 0
navigation:
  - name: Blog
    id: 09bc36c6-a765-4aca-9e51-b07419c4d8e1
    type: content
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: cysfilm
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F2F2F2'
    - '#00EDED'
    - '#E64C4E'
    - '#EEA7A5'
    - '#6D6D6D'
  brandStrength: 0
  lightness: 0.7957447
  saturation: 0.4497728
  rhythmicContrast: 0.3318997
purpose: []
